# Generated by Django 3.0.8 on 2020-07-09 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0004_checkout_payment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='course_idd',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
