# Generated by Django 3.0.8 on 2020-07-15 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0005_checkout_course_idd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursedetails',
            name='lectures',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
