# Generated by Django 3.0.8 on 2020-07-16 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0006_auto_20200715_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursedetails',
            name='lectures',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='GoToCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lect', models.CharField(blank=True, max_length=500, null=True)),
                ('title', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MyApp.CourseDetails')),
            ],
        ),
    ]
