# Generated by Django 3.0.8 on 2020-07-16 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0007_auto_20200717_0107'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GoToCourse',
            new_name='LecturesModel',
        ),
    ]
