# Generated by Django 3.0.8 on 2020-07-17 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0008_auto_20200717_0113'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lecturesmodel',
            old_name='title',
            new_name='course',
        ),
    ]
