# Generated by Django 3.0.8 on 2020-07-25 18:17

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0009_auto_20200717_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturesmodel',
            name='lect',
            field=embed_video.fields.EmbedVideoField(blank=True, null=True),
        ),
    ]
