# Generated by Django 3.0.8 on 2020-08-02 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0011_auto_20200726_0000'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturesmodel',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lecturesmodel',
            name='type',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
