# Generated by Django 3.0.8 on 2020-08-02 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0012_auto_20200803_0025'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturesmodel',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
