# Generated by Django 3.0.8 on 2020-08-02 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0013_lecturesmodel_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturesmodel',
            name='time',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
