# Generated by Django 3.0.8 on 2020-08-10 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0016_auto_20200803_0254'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturesmodel',
            name='lect_number',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
